export interface ExportSupport { canonical_id:string; name:string; ciudad:string; tipo_soporte:string; address?:string; description?:string; characteristics?:string; approvedPriceWithTax?:number; imageUrl?:string; image_url?:string; }
export interface ExportLead { name:string; email:string; company?:string; phone?:string; }

const clean=(v:string|undefined)=>(v||'').replace(/\r?\n/g,' ').trim();
const esc=(v:string|undefined)=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const html=(v:string|undefined)=>clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const money=(v:number|undefined)=>Number(v)>0?`ARS ${Number(v).toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'';
const wrap=(v:string,max=76)=>{const out:string[]=[];let line='';for(const w of esc(v).split(/\s+/).filter(Boolean)){const n=line?`${line} ${w}`:w;if(n.length>max&&line){out.push(line);line=w;}else line=n;}if(line)out.push(line);return out;};
const text=(l:string[],value:string,x:number,y:number,size:number,bold=false)=>{l.push('BT',`/${bold?'F2':'F1'} ${size} Tf`,`${x} ${y} Td`,`(${esc(value)}) Tj`,'ET');};
const box=(l:string[],x:number,y:number,w:number,h:number,fill:string,stroke?:string)=>{l.push(`${fill} rg`,`${x} ${y} ${w} ${h} re f`);if(stroke)l.push(`${stroke} RG`,`${x} ${y} ${w} ${h} re S`);};

function makePdf(lead:ExportLead,supports:ExportSupport[],requestId:string){
 const groups:ExportSupport[][]=[];for(let i=0;i<supports.length;i+=4)groups.push(supports.slice(i,i+4));if(!groups.length)groups.push([]);
 const total=supports.reduce((a,s)=>a+(Number(s.approvedPriceWithTax)||0),0);const pagesData:string[][]=[];
 groups.forEach((group,pi)=>{const l:string[]=[];box(l,0,0,595,842,'0.98 0.98 0.96');box(l,0,792,595,50,'0.025 0.263 0.29');text(l,'GRUPO COMUNICARTE',40,815,16,true);text(l,'MEDIA KIT',445,815,9,true);text(l,`Solicitud ${requestId}`,40,768,9);text(l,`Cliente: ${lead.name}`,40,748,11,true);if(lead.company)text(l,`Empresa: ${lead.company}`,40,731,9);text(l,`Soportes: ${supports.length}`,430,748,9);let y=700;
 group.forEach((s,i)=>{const h=142;box(l,40,y-h,515,h,'1 1 1','0.86 0.88 0.87');box(l,40,y-h,7,h,'0.03 0.75 0.54');text(l,`${pi*4+i+1}. ${s.name}`,62,y-25,13,true);text(l,`${s.ciudad}  ·  ${s.tipo_soporte}`,62,y-45,9);if(s.approvedPriceWithTax)text(l,money(s.approvedPriceWithTax),395,y-25,11,true);if(s.address)text(l,`Direccion: ${s.address}`,62,y-62,8);let dy=y-81;wrap(`Descripcion: ${s.description||'Sin descripcion'}`,68).slice(0,2).forEach(v=>{text(l,v,62,dy,8);dy-=11;});wrap(`Caracteristicas: ${s.characteristics||'Sin detalle'}`,68).slice(0,2).forEach(v=>{text(l,v,62,dy,8);dy-=11;});y-=158;});
 if(pi===groups.length-1){box(l,40,42,515,78,'0.93 0.98 0.96');text(l,'RESUMEN DE LA SOLICITUD',58,98,9,true);text(l,`Soportes seleccionados: ${supports.length}`,58,78,8);if(total>0){text(l,'Inversion estimada',370,98,8);text(l,money(total),370,78,12,true);}text(l,'Disponibilidad sujeta a confirmacion comercial.',58,58,7);}text(l,`Grupo Comunicarte · Media Kit · Pagina ${pi+1}/${groups.length}`,40,24,7);pagesData.push(l);});
 const o:string[]=[];o[1]='<< /Type /Catalog /Pages 2 0 R >>';o[2]='PAGES';o[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';o[4]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';let id=5;const pages:number[]=[];for(const lines of pagesData){const c=id++,p=id++,stream=lines.join('\n');o[c]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;o[p]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${c} 0 R >>`;pages.push(p);}o[2]=`<< /Type /Pages /Kids [${pages.map(p=>`${p} 0 R`).join(' ')}] /Count ${pages.length} >>`;let pdf='%PDF-1.4\n';const offsets=[0];for(let i=1;i<o.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${o[i]}\nendobj\n`;}const x=pdf.length;pdf+=`xref\n0 ${o.length}\n0000000000 65535 f \n`;for(let i=1;i<o.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${o.length} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return new Blob([new TextEncoder().encode(pdf)],{type:'application/pdf'});
}

function makePpt(lead:ExportLead,supports:ExportSupport[],requestId:string){const total=supports.reduce((a,s)=>a+(Number(s.approvedPriceWithTax)||0),0);const cover=`<section style="page-break-after:always;width:960px;height:540px;padding:56px;background:#06434A;color:#FAF9F5;font-family:Inter,Arial,sans-serif;box-sizing:border-box"><div style="font-size:15px;font-weight:800;letter-spacing:.08em">GRUPO COMUNICARTE</div><div style="margin-top:120px;font-size:46px;font-weight:800">MEDIA KIT</div><div style="margin-top:18px;font-size:20px;opacity:.85">Solicitud ${html(requestId)}</div><div style="margin-top:90px;font-size:15px">${html(lead.name)}${lead.company?` · ${html(lead.company)}`:''}</div></section>`;const slides=supports.map((s,i)=>`<section style="page-break-after:always;width:960px;height:540px;padding:44px;background:#FAF9F5;color:#172120;font-family:Inter,Arial,sans-serif;box-sizing:border-box"><div style="font-size:13px;color:#06434A;font-weight:800;letter-spacing:.08em">GRUPO COMUNICARTE · MEDIA KIT</div><div style="margin-top:26px;padding:28px;background:#fff;border:1px solid #dfe5e3;border-left:7px solid #07BE8A;border-radius:8px"><div style="display:flex;justify-content:space-between;gap:24px"><div><h1 style="font-size:30px;margin:0 0 10px">${html(s.name)}</h1><div style="font-size:15px;color:#53615f">${html(s.ciudad)} · ${html(s.tipo_soporte)}</div></div>${s.approvedPriceWithTax?`<div style="font-size:22px;font-weight:800;color:#06434A">${html(money(s.approvedPriceWithTax))}</div>`:''}</div><div style="margin-top:24px;font-size:14px"><b>Direccion:</b> ${html(s.address||'No informada')}</div><div style="margin-top:14px;font-size:14px;line-height:1.5"><b>Descripcion:</b> ${html(s.description||'Sin descripcion')}</div><div style="margin-top:12px;font-size:14px;line-height:1.5"><b>Caracteristicas:</b> ${html(s.characteristics||'Sin detalle')}</div></div><div style="margin-top:20px;font-size:11px;color:#73807d">Solicitud ${html(requestId)} · Soporte ${i+1} de ${supports.length}</div></section>`).join('');const summary=`<section style="width:960px;height:540px;padding:52px;background:#06434A;color:#FAF9F5;font-family:Inter,Arial,sans-serif;box-sizing:border-box"><div style="font-size:13px;font-weight:800;letter-spacing:.08em">RESUMEN</div><h1 style="font-size:38px;margin:24px 0">${supports.length} soportes seleccionados</h1><div style="font-size:20px;opacity:.9">${total>0?`Inversion estimada: <b>${html(money(total))}</b>`:'Inversion sujeta a cotizacion'}</div><div style="margin-top:170px;font-size:13px;opacity:.75">Disponibilidad sujeta a confirmacion comercial.</div></section>`;return new Blob([`<html><head><meta charset="utf-8"></head><body style="margin:0">${cover}${slides}${summary}</body></html>`],{type:'application/vnd.ms-powerpoint'});}

export function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function downloadMediaKitPdf(lead:ExportLead,supports:ExportSupport[],requestId:string){downloadBlob(makePdf(lead,supports,requestId),`media-kit-${requestId}.pdf`);}
export function downloadMediaKitPpt(lead:ExportLead,supports:ExportSupport[],requestId:string){downloadBlob(makePpt(lead,supports,requestId),`media-kit-${requestId}.ppt`);}
export async function sendMediaKitToLead(lead:ExportLead,supports:ExportSupport[],requestId:string){const pdf=makePdf(lead,supports,requestId),ppt=makePpt(lead,supports,requestId);const files=[new File([pdf],`media-kit-${requestId}.pdf`,{type:'application/pdf'}),new File([ppt],`media-kit-${requestId}.ppt`,{type:'application/vnd.ms-powerpoint'})];if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){await navigator.share({title:`Media Kit ${requestId}`,text:`Media Kit aprobado para ${lead.name}.`,files});return 'shared';}window.location.href=`mailto:${encodeURIComponent(lead.email)}?subject=${encodeURIComponent(`Media Kit ${requestId} - Grupo Comunicarte`)}&body=${encodeURIComponent(`Hola ${lead.name},\n\nAdjuntá el Media Kit aprobado (${requestId}).\n\nSaludos,\nGrupo Comunicarte`)}`;return 'mailto';}
