export interface ExportSupport {
  canonical_id: string;
  name: string;
  ciudad: string;
  tipo_soporte: string;
  address?: string;
  description?: string;
  characteristics?: string;
}
export interface ExportLead { name: string; email: string; company?: string; phone?: string; }
const clean=(v:string|undefined)=>(v||'').replace(/\r?\n/g,' ').trim();
const escPdf=(v:string)=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^\x20-\x7E]/g,'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const escHtml=(v:string)=>clean(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
function wrap(v:string,max=86){const out:string[]=[];let cur='';for(const word of escPdf(v).split(/\s+/).filter(Boolean)){const next=cur?`${cur} ${word}`:word;if(next.length>max&&cur){out.push(cur);cur=word;}else cur=next;}if(cur)out.push(cur);return out;}
function pdfStream(lead:ExportLead,supports:ExportSupport[],requestId:string){const l:string[]=['BT','/F1 20 Tf','50 790 Td','(Grupo Comunicarte - Media Kit) Tj','/F1 10 Tf','0 -24 Td',`(Solicitud: ${escPdf(requestId)}) Tj`,'0 -16 Td',`(Cliente: ${escPdf(lead.name)}) Tj`];if(lead.company)l.push('0 -14 Td',`(Empresa: ${escPdf(lead.company)}) Tj`);l.push('0 -14 Td',`(Email: ${escPdf(lead.email)}) Tj`);if(lead.phone)l.push('0 -14 Td',`(Telefono: ${escPdf(lead.phone)}) Tj`);l.push('0 -24 Td','/F1 13 Tf','(Soportes seleccionados) Tj','/F1 10 Tf');supports.forEach((s,i)=>{l.push('0 -22 Td','/F1 12 Tf',`(${i+1}. ${escPdf(s.name)}) Tj`,'/F1 9 Tf','0 -13 Td',`(Ubicacion: ${escPdf(s.ciudad)}) Tj`,'0 -13 Td',`(Tipo: ${escPdf(s.tipo_soporte)}) Tj`);if(s.address)l.push('0 -13 Td',`(Direccion: ${escPdf(s.address)}) Tj`);for(const line of wrap(`Descripcion: ${s.description||''}`,88).slice(0,2))l.push('0 -13 Td',`(${line}) Tj`);for(const line of wrap(`Caracteristicas: ${s.characteristics||''}`,88).slice(0,2))l.push('0 -13 Td',`(${line}) Tj`);});l.push('0 -24 Td','/F1 8 Tf','(Documento comercial informativo. Disponibilidad sujeta a confirmacion.) Tj','ET');return l.join('\n');}
function createPdf(lead:ExportLead,supports:ExportSupport[],requestId:string){const groups:ExportSupport[][]=[];for(let i=0;i<supports.length;i+=8)groups.push(supports.slice(i,i+8));if(!groups.length)groups.push([]);const o:string[]=[];const pages:number[]=[];o[1]='<< /Type /Catalog /Pages 2 0 R >>';o[2]='PAGES';o[3]='<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';let id=4;for(const group of groups){const content=id++,page=id++;const stream=pdfStream(lead,group,requestId);o[content]=`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;o[page]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents ${content} 0 R >>`;pages.push(page);}o[2]=`<< /Type /Pages /Kids [${pages.map(p=>`${p} 0 R`).join(' ')}] /Count ${pages.length} >>`;let pdf='%PDF-1.4\n';const offsets=[0];for(let i=1;i<o.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${o[i]}\nendobj\n`;}const x=pdf.length;pdf+=`xref\n0 ${o.length}\n0000000000 65535 f \n`;for(let i=1;i<o.length;i++)pdf+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;pdf+=`trailer\n<< /Size ${o.length} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return new Blob([new TextEncoder().encode(pdf)],{type:'application/pdf'});}
function createPpt(lead:ExportLead,supports:ExportSupport[],requestId:string){const slides=supports.map((s,i)=>`<section style="page-break-after:always;width:960px;height:540px;padding:48px;font-family:Arial,sans-serif;box-sizing:border-box"><div style="font-size:16px;color:#0f766e;font-weight:700">GRUPO COMUNICARTE · MEDIA KIT</div><h1 style="font-size:34px;margin:24px 0 10px">${escHtml(s.name)}</h1><p style="font-size:18px;color:#555">${escHtml(s.ciudad)} · ${escHtml(s.tipo_soporte)}</p><p style="font-size:18px;margin-top:28px"><b>Dirección:</b> ${escHtml(s.address||'No informada')}</p><p style="font-size:18px"><b>Descripción:</b> ${escHtml(s.description||'Sin descripción')}</p><p style="font-size:18px"><b>Características:</b> ${escHtml(s.characteristics||'Sin detalle')}</p><div style="font-size:12px;color:#888;margin-top:42px">Solicitud ${escHtml(requestId)} · Cliente ${escHtml(lead.name)} · Slide ${i+1}</div></section>`).join('');return new Blob([`<html><head><meta charset="utf-8"></head><body>${slides||`<section><h1>Media Kit</h1><p>${escHtml(requestId)}</p></section>`}</body></html>`],{type:'application/vnd.ms-powerpoint'});}
export function downloadBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function downloadMediaKitPdf(lead:ExportLead,supports:ExportSupport[],requestId:string){downloadBlob(createPdf(lead,supports,requestId),`media-kit-${requestId}.pdf`);}
export function downloadMediaKitPpt(lead:ExportLead,supports:ExportSupport[],requestId:string){downloadBlob(createPpt(lead,supports,requestId),`media-kit-${requestId}.ppt`);}
export async function sendMediaKitToLead(lead:ExportLead,supports:ExportSupport[],requestId:string){const pdf=createPdf(lead,supports,requestId),ppt=createPpt(lead,supports,requestId);const files=[new File([pdf],`media-kit-${requestId}.pdf`,{type:'application/pdf'}),new File([ppt],`media-kit-${requestId}.ppt`,{type:'application/vnd.ms-powerpoint'})];if(typeof navigator!=='undefined'&&navigator.share&&(!navigator.canShare||navigator.canShare({files}))){await navigator.share({title:`Media Kit ${requestId}`,text:`Media Kit preparado para ${lead.name}.`,files});return 'shared';}window.location.href=`mailto:${encodeURIComponent(lead.email)}?subject=${encodeURIComponent(`Media Kit ${requestId} - Grupo Comunicarte`)}&body=${encodeURIComponent(`Hola ${lead.name},\n\nAdjuntá a este correo los archivos Media Kit descargados (${requestId}).\n\nSaludos,\nGrupo Comunicarte`)}`;return 'mailto';}
