import crypto from 'crypto';
import { and, eq, inArray } from 'drizzle-orm';
import { db, isDatabaseConfigured } from '../db/index.ts';
import { fixedLocations, mobileRoutes } from '../data/inventory.ts';
import { supportFaces, supportLocations, supportMedia, supportPricing, supports, supportRoutes, supportTechnical } from '../db/schema.ts';
import { Disponibilidad, InventoryItem, LocationRecord, MobileRoute, Plaza, SupportCurrency, SupportFamily, SupportMediaItem, SupportMediaType, SupportPricing, SupportRouteData, SupportTechnicalData, TipoSoporte } from '../types.ts';

export const ALLOWED_FAMILIES: SupportFamily[] = ['traditional', 'medium_format', 'led', 'led_mobile'];
export const ALLOWED_MEDIA_TYPES: SupportMediaType[] = ['image', 'video', 'document'];
export const ALLOWED_DISPONIBILIDADES: Disponibilidad[] = ['disponible', 'reservado', 'inactivo'];
export const ALLOWED_CIUDADES: Plaza[] = ['mendoza', 'buenos-aires'];

type SupportRow = typeof supports.$inferSelect;
type SupportLocationRow = typeof supportLocations.$inferSelect;
type SupportTechnicalRow = typeof supportTechnical.$inferSelect;
type SupportPricingRow = typeof supportPricing.$inferSelect;
type SupportRouteRow = typeof supportRoutes.$inferSelect;
type SupportMediaRow = typeof supportMedia.$inferSelect;
type SupportFaceRow = typeof supportFaces.$inferSelect;

export interface SupportMediaInput { media_type: SupportMediaType; url: string; title?: string; alt?: string; mime_type?: string; sort_order?: number; metadata?: Record<string, unknown>; active?: boolean; }
export interface SupportFaceInput { face_key: string; label: string; side?: string; width_meters?: number | null; height_meters?: number | null; width_pixels?: number | null; height_pixels?: number | null; substrate?: string; notes?: string; active?: boolean; sort_order?: number; metadata?: Record<string, unknown>; }
export interface SupportWritePayload { name?: string; ciudad?: Plaza; family?: SupportFamily; category?: SupportFamily; tipo_soporte?: TipoSoporte; lat?: number | string | null; lng?: number | string | null; address?: string; description?: string; characteristics?: string; mapa_url?: string; imageUrls?: string[]; disponibilidad?: Disponibilidad; availableFrom?: string | null; isFeatured?: boolean; active?: boolean; technical?: Partial<SupportTechnicalData>; pricing?: Partial<SupportPricing> & { currency?: SupportCurrency | string }; route?: Partial<SupportRouteData>; media?: SupportMediaInput[]; faces?: SupportFaceInput[]; }

function hasOwn<T extends object>(obj: T, key: PropertyKey): boolean { return Object.prototype.hasOwnProperty.call(obj, key); }
function normalizeText(value: unknown): string { return typeof value === 'string' ? value.trim() : ''; }
function toNullableNumber(value: unknown): number | null { if (value === null || value === undefined || value === '') return null; const parsed = typeof value === 'number' ? value : Number(value); return Number.isFinite(parsed) ? parsed : null; }
function toSnakeCase(value: string): string { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }
export function resolveFamily(payload: SupportWritePayload, currentTipo?: TipoSoporte | null): SupportFamily { const raw = (payload.family || payload.category || currentTipo || 'traditional').toString(); if (raw === 'tradicional' || raw === 'traditional') return 'traditional'; if (raw === 'medio_formato' || raw === 'medium_format' || raw === 'medium-format') return 'medium_format'; if (raw === 'led_movil' || raw === 'led_mobile' || raw === 'mobile_led') return 'led_mobile'; if (raw === 'led') return 'led'; if (ALLOWED_FAMILIES.includes(raw as SupportFamily)) return raw as SupportFamily; return 'traditional'; }
export function familyToTipoSoporte(family: SupportFamily): TipoSoporte { if (family === 'led') return 'led'; if (family === 'led_mobile') return 'led_movil'; return 'tradicional'; }
export function validateFamily(family: string): asserts family is SupportFamily { if (!ALLOWED_FAMILIES.includes(family as SupportFamily)) throw new Error(`Categoría desconocida: ${family}`); }
export function validateMediaType(mediaType: string): asserts mediaType is SupportMediaType { if (!ALLOWED_MEDIA_TYPES.includes(mediaType as SupportMediaType)) throw new Error(`media_type inválido: ${mediaType}`); }
export function validateAvailability(value: unknown): asserts value is Disponibilidad { if (!ALLOWED_DISPONIBILIDADES.includes(value as Disponibilidad)) throw new Error(`Disponibilidad inválida: ${String(value)}`); }
export function validateCoordinates(lat: unknown, lng: unknown) { const latValue = toNullableNumber(lat); const lngValue = toNullableNumber(lng); if ((lat != null && lat !== '') !== (lng != null && lng !== '')) throw new Error('Coordenadas inválidas: lat y lng deben enviarse juntas o ambas omitirse.'); if ((lat != null && lat !== '' && latValue === null) || (lng != null && lng !== '' && lngValue === null)) throw new Error('Coordenadas inválidas: lat/lng deben ser valores numéricos válidos.'); if (latValue !== null && (latValue < -90 || latValue > 90)) throw new Error(`Coordenadas inválidas: lat fuera de rango (${latValue}).`); if (lngValue !== null && (lngValue < -180 || lngValue > 180)) throw new Error(`Coordenadas inválidas: lng fuera de rango (${lngValue}).`); return { lat: latValue, lng: lngValue }; }
export function validatePricingInput(pricing?: Partial<SupportPricing> & { currency?: SupportCurrency | string }) { if (!pricing) return; const fields = ['exhibition_price','installation_price','printing_price','monthly_price','exclusive_price'] as const; for (const field of fields) { const value = (pricing as Record<string, unknown>)[field]; if (value === undefined || value === null || value === '') continue; const numericValue = Number(value); if (!Number.isFinite(numericValue) || numericValue < 0) throw new Error(`Precio negativo o inválido en ${field}`); } if (pricing.currency && !['ARS','USD'].includes(String(pricing.currency))) throw new Error(`Moneda inválida: ${pricing.currency}`); }
export function validateSupportPayload(payload: SupportWritePayload) { const name = normalizeText(payload.name); if (!name) throw new Error('name vacío'); const city = normalizeText(payload.ciudad); if (city && !ALLOWED_CIUDADES.includes(city as Plaza)) throw new Error(`ciudad inválida: ${city}`); const family = resolveFamily(payload); validateFamily(family); if (payload.disponibilidad !== undefined) validateAvailability(payload.disponibilidad); const { lat, lng } = validateCoordinates(payload.lat, payload.lng); validatePricingInput(payload.pricing); return { name, ciudad: (city || 'mendoza') as Plaza, family, tipo_soporte: familyToTipoSoporte(family), lat, lng, address: normalizeText(payload.address), description: normalizeText(payload.description), characteristics: normalizeText(payload.characteristics), mapa_url: normalizeText(payload.mapa_url), imageUrls: Array.isArray(payload.imageUrls) ? payload.imageUrls.filter((item) => typeof item === 'string' && item.trim()) : [], disponibilidad: payload.disponibilidad ?? 'disponible', availableFrom: payload.availableFrom === undefined ? undefined : payload.availableFrom === null ? null : normalizeText(payload.availableFrom), isFeatured: payload.isFeatured ?? false, active: payload.active ?? true }; }
function mapPricingRow(row: SupportPricingRow | null | undefined): SupportPricing | null { if (!row) return null; return { exhibition_price: row.exhibitionPrice == null ? 0 : Number(row.exhibitionPrice), installation_price: row.installationPrice == null ? 0 : Number(row.installationPrice), printing_price: row.printingPrice == null ? 0 : Number(row.printingPrice), monthly_price: row.monthlyPrice == null ? 0 : Number(row.monthlyPrice), exclusive_price: row.exclusivePrice == null ? 0 : Number(row.exclusivePrice), currency: (row.currency as SupportCurrency) || 'ARS', tax_included: row.taxIncluded ?? false, price_public: row.pricePublic ?? false }; }
function mapMediaRows(rows: SupportMediaRow[]): SupportMediaItem[] { return rows.slice().sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0)||a.id-b.id).map(row=>({ id:row.id, media_type:row.mediaType as SupportMediaType, url:row.url, title:row.title||undefined, alt:row.alt||undefined, mime_type:row.mimeType||undefined, sort_order:row.sortOrder, metadata:(row.metadata as Record<string,unknown>)||undefined, active:row.active??true })); }
function mapTechnicalRow(row: SupportTechnicalRow | null | undefined): SupportTechnicalData | null { if (!row) return null; const metadata = (row.metadata as Record<string, unknown>) || undefined; const monthlyImpacts = metadata?.monthly_impacts ?? metadata?.monthlyImpacts ?? metadata?.impactos_mensuales; return { summary:row.summary||undefined, measures:row.measures||undefined, resolution:row.resolution||undefined, turn_on_schedule:row.turnOnSchedule||undefined, daily_frequency:row.dailyFrequency||undefined, requirements:row.requirements||undefined, monthly_impacts: typeof monthlyImpacts === 'number' || typeof monthlyImpacts === 'string' ? monthlyImpacts : null, spot_duration_seconds:row.spotDurationSeconds??null, minimum_daily_outings:row.minimumDailyOutings??null, max_advertisers:row.maxAdvertisers??null, route_duration_hours:row.routeDurationHours==null?null:Number(row.routeDurationHours), operation_days:row.operationDays||undefined, video_mode:row.videoMode||undefined, metadata }; }
function mapRouteRow(row: SupportRouteRow | null | undefined): SupportRouteData | null { if (!row) return null; return { route_name:row.routeName||undefined, route_mode:row.routeMode||undefined, routePath:(row.routePath as [number,number][])||[], waypoints:(row.waypoints as {name:string;lat:number|null;lng:number|null}[])||[], default_route:row.defaultRoute??false, schedule:row.schedule||undefined, duration:row.duration||undefined, hours:row.hours||undefined, weekdays:row.weekdays||undefined, max_advertisers:row.maxAdvertisers??null, spot_duration_seconds:row.spotDurationSeconds??null, minimum_daily_outings:row.minimumDailyOutings??null, metadata:(row.metadata as Record<string,unknown>)||undefined }; }
async function loadRelatedRecords(canonicalIds:string[]){ if(canonicalIds.length===0)return {locations:new Map(),technical:new Map(),pricing:new Map(),routes:new Map(),media:new Map(),faces:new Map()}; const [locationsRows,technicalRows,pricingRows,routeRows,mediaRows,faceRows]=await Promise.all([db.select().from(supportLocations).where(inArray(supportLocations.supportCanonicalId,canonicalIds)),db.select().from(supportTechnical).where(inArray(supportTechnical.supportCanonicalId,canonicalIds)),db.select().from(supportPricing).where(inArray(supportPricing.supportCanonicalId,canonicalIds)),db.select().from(supportRoutes).where(inArray(supportRoutes.supportCanonicalId,canonicalIds)),db.select().from(supportMedia).where(inArray(supportMedia.supportCanonicalId,canonicalIds)),db.select().from(supportFaces).where(inArray(supportFaces.supportCanonicalId,canonicalIds))]); const locations=new Map<string,SupportLocationRow>(),technical=new Map<string,SupportTechnicalRow>(),pricing=new Map<string,SupportPricingRow>(),routes=new Map<string,SupportRouteRow>(),media=new Map<string,SupportMediaRow[]>(),faces=new Map<string,SupportFaceRow[]>(); for(const row of locationsRows)locations.set(row.supportCanonicalId,row); for(const row of technicalRows)technical.set(row.supportCanonicalId,row); for(const row of pricingRows)pricing.set(row.supportCanonicalId,row); for(const row of routeRows)routes.set(row.supportCanonicalId,row); for(const row of mediaRows){const current=media.get(row.supportCanonicalId)||[];current.push(row);media.set(row.supportCanonicalId,current);} for(const row of faceRows){const current=faces.get(row.supportCanonicalId)||[];current.push(row);faces.set(row.supportCanonicalId,current);} return {locations,technical,pricing,routes,media,faces}; }

function rowToInventoryItem(row: SupportRow, related: Awaited<ReturnType<typeof loadRelatedRecords>>): InventoryItem { const location=related.locations.get(row.canonicalId); const technical=related.technical.get(row.canonicalId); const pricing=related.pricing.get(row.canonicalId); const route=related.routes.get(row.canonicalId); const media=mapMediaRows(related.media.get(row.canonicalId)||[]); const family=(row.family as SupportFamily)||resolveFamily({tipo_soporte:row.tipoSoporte as TipoSoporte}); const isMobile=family==='led_mobile'||row.tipoSoporte==='led_movil'; const imageUrls=media.filter(e=>e.media_type==='image'&&e.active!==false).map(e=>e.url); const fallbackImages=(row.imageUrls as string[])||[]; const base={canonical_id:row.canonicalId,name:row.name,ciudad:row.ciudad as Plaza,tipo_soporte:familyToTipoSoporte(family),family,active:row.active??true,description:row.description||'',characteristics:row.characteristics||'',mapa_url:row.mapaUrl||'',imageUrls:imageUrls.length?imageUrls:fallbackImages,disponibilidad:(row.disponibilidad as Disponibilidad)||'disponible',availableFrom:row.availableFrom||undefined,isFeatured:row.isFeatured??false,pricing:mapPricingRow(pricing),media,technical:mapTechnicalRow(technical)}; if(isMobile)return {...base,address:location?.address||row.address||'',schedule:route?.schedule||row.schedule||'',duration:route?.duration||row.duration||'',waypoints:route?.waypoints||row.waypoints||[],routePath:route?.routePath||row.routePath||[]} as MobileRoute; return {...base,lat:location?.lat==null?(row.lat==null?null:Number(row.lat)):Number(location.lat),lng:location?.lng==null?(row.lng==null?null:Number(row.lng)):Number(location.lng),address:location?.address||row.address||'',description:row.description||'',characteristics:row.characteristics||''} as LocationRecord; }

export async function listSupports(): Promise<InventoryItem[]> { if(!isDatabaseConfigured()) return [...fixedLocations,...mobileRoutes].filter(item=>item.active!==false); const rows=await db.select().from(supports).where(eq(supports.active,true)); const related=await loadRelatedRecords(rows.map(row=>row.canonicalId)); return rows.map(row=>rowToInventoryItem(row,related)); }

export async function getSupportById(canonicalId:string):Promise<InventoryItem|null>{ if(!isDatabaseConfigured()) return [...fixedLocations,...mobileRoutes].find(item=>item.canonical_id===canonicalId)||null; const rows=await db.select().from(supports).where(eq(supports.canonicalId,canonicalId)); if(!rows[0])return null; const related=await loadRelatedRecords([canonicalId]); return rowToInventoryItem(rows[0],related); }
