import { useEffect, useMemo, useState } from 'react';
import { Download, Eye, FileText, Loader2, RefreshCw, Send, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { DashboardShell } from '../../components/dashboard/DashboardShell';
import { apiFetch } from '../../lib/api';
import { calculateSupportTotal, formatSupportCurrency } from '../../lib/supportPricing';
import { downloadMediaKitPdf, downloadMediaKitPpt, sendMediaKitToLead, ExportLead, ExportSupport } from '../../lib/adminMediaKitExport';

type WorkflowStatus = 'request' | 'in_progress' | 'done';
type Pricing = { exhibition_price?: number | string | null; installation_price?: number | string | null; printing_price?: number | string | null; currency?: string | null };
type LeadRequest = { id:string; requestId:string; clientName:string; email:string; company:string; phone:string; message:string; status:WorkflowStatus; supportIds:string[]; supportNames:string[]; createdAt:string };
type SupportForKit = ExportSupport & { pricing?: Pricing | null };
const labels:Record<WorkflowStatus,string>={request:'REQUEST',in_progress:'IN PROGRESS',done:'DONE'};
function toWorkflowStatus(status:string):WorkflowStatus { if(status==='contactado'||status==='in_progress') return 'in_progress'; if(status==='enviado'||status==='quoted'||status==='done'||status==='cerrado') return 'done'; return 'request'; }

export default function DashboardMediaKitWorkflow(){
  const navigate=useNavigate();
  const [leads,setLeads]=useState<LeadRequest[]>([]); const [filter,setFilter]=useState<'all'|WorkflowStatus>('all'); const [selected,setSelected]=useState<LeadRequest|null>(null); const [supports,setSupports]=useState<SupportForKit[]>([]); const [approvedPrices,setApprovedPrices]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const [toast,setToast]=useState('');
  const notify=(m:string)=>{setToast(m);window.setTimeout(()=>setToast(''),2500)};
  const load=async()=>{const token=localStorage.getItem('admin_token');if(!token){navigate('/login');return;}const r=await apiFetch('/api/admin/requests',{headers:{Authorization:`Bearer ${token}`}});if(r.status===401){localStorage.removeItem('admin_token');navigate('/login');return;}const j=await r.json();if(j.status!=='success')throw new Error(j.message||'No pudimos cargar las solicitudes.');setLeads((j.data||[]).map((x:any)=>({id:String(x.id),requestId:x.requestId,clientName:x.requesterName,email:x.requesterEmail,company:x.requesterCompany||'Particular / Directo',phone:x.requesterPhone||'',message:x.message||'',status:toWorkflowStatus(x.status),supportIds:x.supportIds||[],supportNames:x.supportNames||x.supportIds||[],createdAt:x.createdAt||new Date().toISOString()})));};
  useEffect(()=>{load().catch(e=>notify(e instanceof Error?e.message:'Error al cargar solicitudes.'));},[navigate]);
  const counts=useMemo(()=>({all:leads.length,request:leads.filter(x=>x.status==='request').length,in_progress:leads.filter(x=>x.status==='in_progress').length,done:leads.filter(x=>x.status==='done').length}),[leads]);
  const visible=filter==='all'?leads:leads.filter(x=>x.status===filter);
  const changeStatus=async(lead:LeadRequest,next:WorkflowStatus)=>{setBusy(true);try{const token=localStorage.getItem('admin_token');const persisted=next==='request'?'pending':next==='in_progress'?'contactado':'enviado';const r=await fetch(`/api/admin/requests/${encodeURIComponent(lead.requestId)}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({status:persisted})});const j=await r.json().catch(()=>null);if(!r.ok||j?.status!=='success')throw new Error(j?.message||'No pudimos actualizar el estado.');await load();setSelected(x=>x?{...x,status:next}:null);notify(`Solicitud ${labels[next]}`);}catch(e){notify(e instanceof Error?e.message:'Error al actualizar.');}finally{setBusy(false);}};
  const open=async(lead:LeadRequest)=>{setSelected(lead);setSupports([]);setApprovedPrices({});setLoading(true);try{const r=await fetch('/api/supports');const j=await r.json();if(!r.ok||j.status!=='success')throw new Error('No pudimos cargar los datos del inventario.');const ids=new Set(lead.supportIds);setSupports((j.data||[]).filter((x:any)=>ids.has(x.canonical_id)).map((x:any)=>({canonical_id:x.canonical_id,name:x.name,ciudad:x.ciudad,tipo_soporte:x.tipo_soporte,address:x.address,description:x.description,characteristics:x.characteristics,pricing:x.pricing||null})));}catch(e){notify(e instanceof Error?e.message:'Error al cargar soportes.');}finally{setLoading(false);}};
  const lead=selected?{name:selected.clientName,email:selected.email,company:selected.company,phone:selected.phone}:null;
  const approvalsReady=supports.length>0 && supports.every(s=>{const v=Number(approvedPrices[s.canonical_id]||0);return Number.isFinite(v)&&v>0;});
  const exportSupports:ExportSupport[]=supports.map(s=>({...s,approvedPriceWithTax:Number(approvedPrices[s.canonical_id]||0)} as ExportSupport));
  return <DashboardShell><div className="max-w-7xl space-y-6">{toast&&<div role="status" className="fixed right-6 top-20 z-50 rounded-xl bg-gray-900 px-4 py-2.5 text-xs font-bold text-white shadow-lg">{toast}</div>}
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-eyebrow text-emerald-700">GESTIÓN COMERCIAL</div><h1 className="mt-2 text-page-title text-gray-900">Solicitudes de Media Kit</h1><p className="mt-1 text-sm text-gray-500">REQUEST → IN PROGRESS → DONE. La generación y entrega pertenecen al equipo comercial.</p></div><button onClick={()=>load().catch(()=>notify('No pudimos actualizar la bandeja.'))} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-3.5 py-2 text-xs font-bold text-gray-700"><RefreshCw className="h-3.5 w-3.5"/>Actualizar</button></header>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{([['all','Todas',counts.all],['request','REQUEST',counts.request],['in_progress','IN PROGRESS',counts.in_progress],['done','DONE',counts.done]] as const).map(([v,l,c])=><button key={v} onClick={()=>setFilter(v)} className={`rounded-2xl border p-4 text-left ${filter===v?'border-gray-900 bg-gray-900 text-white':'border-gray-200 bg-white text-gray-800'}`}><span className="block text-[10px] font-bold uppercase tracking-wider opacity-70">{l}</span><span className="mt-1 block text-2xl font-extrabold">{c}</span></button>)}</div>
    <div className="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b border-gray-200 bg-gray-50 text-[11px] uppercase tracking-wider text-gray-500"><tr><th className="px-4 py-3">Solicitud</th><th className="px-4 py-3">Lead</th><th className="px-4 py-3">Soportes</th><th className="px-4 py-3">Estado</th><th className="px-4 py-3 text-right">Acción</th></tr></thead><tbody className="divide-y divide-gray-100">{visible.map(x=><tr key={x.id}><td className="px-4 py-3"><div className="font-mono font-bold text-gray-400">{x.requestId}</div><div className="text-gray-500">{new Date(x.createdAt).toLocaleString('es-AR')}</div></td><td className="px-4 py-3"><div className="font-bold text-gray-900">{x.clientName}</div><div className="text-gray-500">{x.company}</div><div className="text-gray-500">{x.email}</div></td><td className="max-w-sm px-4 py-3"><div className="flex flex-wrap gap-1">{x.supportNames.slice(0,3).map((n:string)=><span key={n} className="rounded-md bg-gray-100 px-2 py-1 text-[10px] font-semibold">{n}</span>)}{x.supportNames.length>3&&<span className="px-1 py-1 text-[10px] font-bold text-gray-400">+{x.supportNames.length-3}</span>}</div></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${x.status==='done'?'bg-emerald-50 text-emerald-800':x.status==='in_progress'?'bg-amber-50 text-amber-800':'bg-blue-50 text-blue-800'}`}>{labels[x.status]}</span></td><td className="px-4 py-3 text-right"><button onClick={()=>open(x)} className="inline-flex items-center gap-1.5 rounded-lg border border-gray-200 px-3 py-1.5 font-bold"><Eye className="h-3.5 w-3.5"/>Detalle</button></td></tr>)}{visible.length===0&&<tr><td colSpan={5} className="px-4 py-12 text-center text-gray-400">No hay solicitudes en este estado.</td></tr>}</tbody></table></div></div>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between border-b border-gray-100 pb-4"><div><div className="font-mono text-xs font-bold text-gray-400">{selected.requestId}</div><h2 className="mt-1 text-xl font-bold text-gray-900">{selected.clientName}</h2><p className="mt-1 text-sm text-gray-500">{selected.company} · {selected.email}</p></div><button onClick={()=>setSelected(null)} aria-label="Cerrar" className="rounded-full p-2 text-gray-400 hover:bg-gray-100"><X className="h-5 w-5"/></button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-4"><div className="rounded-xl bg-gray-50 p-3"><div className="text-[9px] font-bold uppercase text-gray-400">Estado</div><div className="mt-1 font-bold">{labels[selected.status]}</div></div><div className="rounded-xl bg-gray-50 p-3"><div className="text-[9px] font-bold uppercase text-gray-400">Teléfono</div><div className="mt-1 font-bold">{selected.phone||'—'}</div></div><div className="rounded-xl bg-gray-50 p-3"><div className="text-[9px] font-bold uppercase text-gray-400">Soportes</div><div className="mt-1 font-bold">{selected.supportIds.length}</div></div><div className={`rounded-xl p-3 ${approvalsReady?'bg-emerald-50':'bg-amber-50'}`}><div className="text-[9px] font-bold uppercase text-gray-500">Precio</div><div className="mt-1 font-bold">{approvalsReady?'Aprobado':'Pendiente'}</div></div></div>
      {selected.message&&<div className="mt-4 rounded-xl bg-gray-50 p-4 text-sm text-gray-700">{selected.message}</div>}
      <div className="mt-5 space-y-3">{loading?<div className="flex items-center gap-2 text-sm text-gray-500"><Loader2 className="h-4 w-4 animate-spin"/>Cargando soportes…</div>:supports.map(s=>{const base=calculateSupportTotal(s.pricing);const approved=approvedPrices[s.canonical_id]||'';return <div key={s.canonical_id} className="rounded-xl border border-gray-200 p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="font-semibold">{s.name}</div><div className="mt-1 text-xs text-gray-500">{s.ciudad} · {s.tipo_soporte}{s.address?` · ${s.address}`:''}</div></div><div className="text-right"><div className="text-[9px] font-bold uppercase text-gray-400">Total soporte interno</div><div className="mt-1 font-extrabold">{formatSupportCurrency(base,s.pricing?.currency||'ARS')}</div></div></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto] md:items-end"><div><label className="text-[10px] font-bold uppercase tracking-wider text-gray-500">Precio Media Kit · IVA incluido</label><input type="number" min="0" value={approved} onChange={e=>setApprovedPrices(prev=>({...prev,[s.canonical_id]:e.target.value}))} className="mt-1 w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-sm font-bold text-gray-900 outline-none focus:border-gray-400 focus:ring-2 focus:ring-gray-100" placeholder="Ingresar precio aprobado" /></div><div className={`rounded-xl px-4 py-2.5 text-xs font-extrabold ${approved&&Number(approved)>0?'bg-emerald-50 text-emerald-800':'bg-gray-50 text-gray-400'}`}>{approved&&Number(approved)>0?'APROBADO':'PENDIENTE'}</div></div></div>})}</div>
      <div className="mt-6 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4"><div className="mb-3 text-sm font-bold text-emerald-950">Workflow comercial</div><div className="flex flex-wrap gap-2">{selected.status==='request'&&<button disabled={busy} onClick={()=>changeStatus(selected,'in_progress')} className="rounded-xl bg-amber-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Pasar a IN PROGRESS</button>}{selected.status==='in_progress'&&<button disabled={busy} onClick={()=>changeStatus(selected,'done')} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">Marcar DONE</button>}{selected.status==='done'&&lead&&<><button disabled={!approvalsReady} onClick={()=>approvalsReady&&downloadMediaKitPdf(lead,exportSupports,selected.requestId)} className="inline-flex items-center gap-1.5 rounded-xl border bg-white px-3 py-2 text-xs font-bold disabled:cursor-not-allowed disabled:opacity-40"><Download className="h-3.5 w-3.5"/>PDF</button><button disabled={!approvalsReady} onClick={()=>approvalsReady&&downloadMediaKitPpt(lead,exportSupports,selected.requestId)} className="inline-flex items-center gap-1.5 rounded-xl border bg-white px-3 py-2 text-xs font-bold disabled:cursor-not-allowed disabled:opacity-40"><FileText className="h-3.5 w-3.5"/>PPT</button><button disabled={!approvalsReady} onClick={async()=>{if(!approvalsReady)return;try{const m=await sendMediaKitToLead(lead,exportSupports,selected.requestId);notify(m==='shared'?'Archivos listos para compartir con el lead.':'Se abrió el correo del lead para adjuntar los archivos.');}catch(e){notify(e instanceof Error?e.message:'No pudimos preparar el envío.');}}} className="inline-flex items-center gap-1.5 rounded-xl bg-gray-900 px-3 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Send className="h-3.5 w-3.5"/>Enviar al lead</button></>}</div>{selected.status==='done'&&!approvalsReady&&<p className="mt-3 text-xs font-semibold text-amber-800">Aprobá el precio Media Kit con IVA incluido para cada soporte antes de generar el PDF/PPT.</p>}</div>
      <div className="mt-5 flex justify-end"><button onClick={()=>setSelected(null)} className="rounded-xl bg-gray-900 px-4 py-2 text-xs font-bold text-white">Cerrar</button></div>
    </div></div>}
  </div></DashboardShell>;
}
