import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Loader2, Save } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { DashboardShell } from '../../components/dashboard/DashboardShell';
import { apiFetch } from '../../lib/api';

const sectionClass = 'rounded-2xl border border-gray-200 bg-white p-5 shadow-2xs';
const inputClass = 'mt-1 w-full rounded-xl border border-gray-200 bg-white px-3.5 py-2.5 text-sm text-gray-900 outline-none transition focus:border-gray-400 focus:ring-2 focus:ring-gray-100';
const labelClass = 'text-xs font-bold uppercase tracking-[0.08em] text-gray-500';

type SupportForm = {
  name: string; ciudad: string; family: string; tipo_soporte: string; active: boolean; disponibilidad: string;
  availableFrom: string; isFeatured: boolean; lat: string; lng: string; address: string; description: string; characteristics: string;
  mapa_url: string; imageUrls: string;
  technical: { summary: string; measures: string; resolution: string; turn_on_schedule: string; daily_frequency: string; requirements: string; spot_duration_seconds: string; minimum_daily_outings: string; max_advertisers: string; route_duration_hours: string; operation_days: string; video_mode: string };
  pricing: { exhibition_price: string; installation_price: string; printing_price: string; monthly_price: string; exclusive_price: string; currency: string; tax_included: boolean; price_public: boolean };
  route: { route_name: string; route_mode: string; schedule: string; duration: string; hours: string; weekdays: string; default_route: boolean; max_advertisers: string; spot_duration_seconds: string; minimum_daily_outings: string; routePath: string; waypoints: string };
};

const emptyForm: SupportForm = {
  name: '', ciudad: 'mendoza', family: 'traditional', tipo_soporte: 'tradicional', active: true, disponibilidad: 'disponible', availableFrom: '', isFeatured: false,
  lat: '', lng: '', address: '', description: '', characteristics: '', mapa_url: '', imageUrls: '',
  technical: { summary: '', measures: '', resolution: '', turn_on_schedule: '', daily_frequency: '', requirements: '', spot_duration_seconds: '0', minimum_daily_outings: '0', max_advertisers: '0', route_duration_hours: '0', operation_days: '', video_mode: '' },
  pricing: { exhibition_price: '0', installation_price: '0', printing_price: '0', monthly_price: '0', exclusive_price: '0', currency: 'ARS', tax_included: false, price_public: false },
  route: { route_name: '', route_mode: 'led_mobile', schedule: '', duration: '', hours: '', weekdays: '', default_route: true, max_advertisers: '8', spot_duration_seconds: '10', minimum_daily_outings: '180', routePath: '[]', waypoints: '[]' },
};

function normalize(item: any): SupportForm {
  const technical = item?.technical || {};
  const pricing = item?.pricing || {};
  const route = item?.route || item || {};
  return {
    ...emptyForm,
    name: item?.name || '', ciudad: item?.ciudad || 'mendoza', family: item?.family || (item?.tipo_soporte === 'led' ? 'led' : item?.tipo_soporte === 'led_movil' ? 'led_mobile' : 'traditional'),
    tipo_soporte: item?.tipo_soporte || 'tradicional', active: item?.active !== false, disponibilidad: item?.disponibilidad || 'disponible', availableFrom: item?.availableFrom || '', isFeatured: !!item?.isFeatured,
    lat: item?.lat == null ? '' : String(item.lat), lng: item?.lng == null ? '' : String(item.lng), address: item?.address || '', description: item?.description || '', characteristics: item?.characteristics || '', mapa_url: item?.mapa_url || '', imageUrls: Array.isArray(item?.imageUrls) ? item.imageUrls.join('\n') : '',
    technical: { ...emptyForm.technical, ...Object.fromEntries(Object.keys(emptyForm.technical).map((k) => [k, technical[k] == null ? emptyForm.technical[k as keyof typeof emptyForm.technical] : String(technical[k])])) },
    pricing: { ...emptyForm.pricing, ...Object.fromEntries(Object.keys(emptyForm.pricing).map((k) => [k, typeof emptyForm.pricing[k as keyof typeof emptyForm.pricing] === 'boolean' ? !!pricing[k] : (pricing[k] == null ? emptyForm.pricing[k as keyof typeof emptyForm.pricing] : String(pricing[k]))])) },
    route: { ...emptyForm.route, route_name: route.route_name || '', route_mode: route.route_mode || 'led_mobile', schedule: route.schedule || '', duration: route.duration || '', hours: route.hours || '', weekdays: route.weekdays || '', default_route: route.default_route ?? true, max_advertisers: String(route.max_advertisers ?? 8), spot_duration_seconds: String(route.spot_duration_seconds ?? 10), minimum_daily_outings: String(route.minimum_daily_outings ?? 180), routePath: JSON.stringify(route.routePath || [], null, 2), waypoints: JSON.stringify(route.waypoints || [], null, 2) },
  };
}

function payloadFrom(form: SupportForm) {
  const payload: any = {
    name: form.name.trim(), ciudad: form.ciudad, family: form.family, tipo_soporte: form.tipo_soporte, active: form.active, disponibilidad: form.disponibilidad,
    availableFrom: form.availableFrom || null, isFeatured: form.isFeatured, lat: form.lat === '' ? null : Number(form.lat), lng: form.lng === '' ? null : Number(form.lng), address: form.address.trim(), description: form.description.trim(), characteristics: form.characteristics.trim(), mapa_url: form.mapa_url.trim(),
    imageUrls: form.imageUrls.split('\n').map((x) => x.trim()).filter(Boolean),
    technical: Object.fromEntries(Object.entries(form.technical).map(([k, v]) => ['spot_duration_seconds','minimum_daily_outings','max_advertisers','route_duration_hours'].includes(k) ? [k, Number(v || 0)] : [k, v])),
    pricing: { ...form.pricing, exhibition_price: Number(form.pricing.exhibition_price || 0), installation_price: Number(form.pricing.installation_price || 0), printing_price: Number(form.pricing.printing_price || 0), monthly_price: Number(form.pricing.monthly_price || 0), exclusive_price: Number(form.pricing.exclusive_price || 0) },
  };
  if (form.family === 'led_mobile') {
    let routePath: unknown[] = []; let waypoints: unknown[] = [];
    try { routePath = JSON.parse(form.route.routePath || '[]'); waypoints = JSON.parse(form.route.waypoints || '[]'); } catch { throw new Error('Ruta inválida: Route Path y Waypoints deben contener JSON válido.'); }
    payload.route = { ...form.route, max_advertisers: Number(form.route.max_advertisers || 0), spot_duration_seconds: Number(form.route.spot_duration_seconds || 0), minimum_daily_outings: Number(form.route.minimum_daily_outings || 0), routePath, waypoints };
  }
  return payload;
}

export default function DashboardSupportEditor({ mode: explicitMode }: { mode?: 'create' | 'edit' }) {
  const { canonicalId } = useParams();
  const navigate = useNavigate();
  const mode = explicitMode || (canonicalId ? 'edit' : 'create');
  const [form, setForm] = useState<SupportForm>(emptyForm);
  const [loading, setLoading] = useState(mode === 'edit'); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [saved, setSaved] = useState(false);
  const set = (patch: Partial<SupportForm>) => setForm((v) => ({ ...v, ...patch }));
  const setNested = (key: 'technical' | 'pricing' | 'route', patch: any) => setForm((v) => ({ ...v, [key]: { ...v[key], ...patch } }));

  useEffect(() => { if (mode !== 'edit' || !canonicalId) return; const run = async () => { try { const token = localStorage.getItem('admin_token'); if (!token) return navigate('/login'); const r = await apiFetch(`/api/admin/supports/${encodeURIComponent(canonicalId)}`, { headers: { Authorization: `Bearer ${token}` } }); const j = await r.json(); if (r.status === 401) return navigate('/login'); if (!r.ok || j.status !== 'success') throw new Error(j.message || 'No se pudo cargar el soporte.'); setForm(normalize(j.data)); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo cargar el soporte.'); } finally { setLoading(false); } }; run(); }, [mode, canonicalId, navigate]);

  const invalid = useMemo(() => form.name.trim().length < 2 || !form.ciudad || !form.tipo_soporte, [form]);
  const save = async () => {
    setError(''); setSaved(false); if (invalid) { setError('Completá al menos nombre, plaza y tipo de soporte.'); return; } setSaving(true);
    try { const token = localStorage.getItem('admin_token'); if (!token) return navigate('/login'); const url = mode === 'create' ? '/api/admin/supports' : `/api/admin/supports/${encodeURIComponent(canonicalId || '')}`; const method = mode === 'create' ? 'POST' : 'PATCH'; const r = await apiFetch(url, { method, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(payloadFrom(form)) }); const j = await r.json(); if (r.status === 401) return navigate('/login'); if (!r.ok || j.status !== 'success') throw new Error(j.message || 'No se pudo guardar el soporte.'); setSaved(true); const id = j.data?.canonical_id || j.data?.canonicalId || canonicalId; if (id) navigate(`/dashboard/soportes/${encodeURIComponent(id)}/edit`, { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar el soporte.'); } finally { setSaving(false); }
  };

  if (loading) return <DashboardShell><div className="mx-auto max-w-5xl py-20 text-center text-sm text-gray-500">Cargando soporte…</div></DashboardShell>;
  return <DashboardShell><div className="mx-auto max-w-6xl space-y-6 pb-10">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><button onClick={() => navigate('/dashboard/soportes')} className="mb-3 inline-flex items-center gap-2 text-xs font-bold text-gray-500 hover:text-gray-900"><ArrowLeft className="h-4 w-4"/>Gestión de Soportes</button><div className="text-eyebrow text-emerald-700">{mode === 'create' ? 'ALTA DE PRODUCTO' : 'EDICIÓN DE PRODUCTO'}</div><h1 className="mt-2 text-page-title text-gray-900">{mode === 'create' ? 'Nuevo soporte' : form.name || 'Editar soporte'}</h1><p className="mt-1 text-sm text-gray-500">Organizado como ficha de producto: primero información comercial y visible, luego datos técnicos.</p></div><div className="flex items-center gap-2"><button onClick={() => navigate('/dashboard/soportes')} className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold text-gray-700">Cancelar</button><button disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin"/> : <Save className="h-4 w-4"/>}{saving ? 'Guardando…' : 'Guardar cambios'}</button></div></header>
    {error && <div role="alert" className="rounded-xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
    {saved && <div role="status" className="inline-flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-4 py-2.5 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4"/>Soporte guardado correctamente.</div>}

    <section className={sectionClass}><h2 className="text-base font-bold text-gray-900">Información del producto</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><label className={labelClass}>Nombre *</label><input className={inputClass} value={form.name} onChange={(e) => set({ name: e.target.value })}/></div><div><label className={labelClass}>Plaza *</label><select className={inputClass} value={form.ciudad} onChange={(e) => set({ ciudad: e.target.value })}><option value="mendoza">Mendoza</option><option value="buenos-aires">Buenos Aires</option></select></div><div><label className={labelClass}>Tipo *</label><select className={inputClass} value={form.tipo_soporte} onChange={(e) => { const t=e.target.value; set({ tipo_soporte:t, family:t==='led'?'led':t==='led_movil'?'led_mobile':'traditional' }); }}><option value="tradicional">Tradicional</option><option value="led">LED</option><option value="led_movil">LED móvil</option></select></div><div><label className={labelClass}>Disponibilidad</label><select className={inputClass} value={form.disponibilidad} onChange={(e) => set({ disponibilidad:e.target.value })}><option value="disponible">Disponible</option><option value="reservado">Reservado</option></select></div><div><label className={labelClass}>Activo</label><select className={inputClass} value={form.active ? 'yes' : 'no'} onChange={(e) => set({ active:e.target.value==='yes' })}><option value="yes">Activo</option><option value="no">Archivado</option></select></div><div><label className={labelClass}>Destacado</label><select className={inputClass} value={form.isFeatured ? 'yes':'no'} onChange={(e)=>set({isFeatured:e.target.value==='yes'})}><option value="no">No</option><option value="yes">Sí</option></select></div></div></section>

    <section className={sectionClass}><h2 className="text-base font-bold text-gray-900">Ubicación</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><label className={labelClass}>Dirección</label><input className={inputClass} value={form.address} onChange={(e)=>set({address:e.target.value})}/></div><div><label className={labelClass}>Latitud</label><input className={inputClass} inputMode="decimal" value={form.lat} onChange={(e)=>set({lat:e.target.value})}/></div><div><label className={labelClass}>Longitud</label><input className={inputClass} inputMode="decimal" value={form.lng} onChange={(e)=>set({lng:e.target.value})}/></div><div className="md:col-span-2"><label className={labelClass}>URL del mapa</label><input className={inputClass} value={form.mapa_url} onChange={(e)=>set({mapa_url:e.target.value})}/></div></div></section>

    <section className={sectionClass}><h2 className="text-base font-bold text-gray-900">Presentación comercial</h2><div className="mt-4 grid gap-4"><div><label className={labelClass}>Descripción</label><textarea className={`${inputClass} min-h-28 resize-y`} value={form.description} onChange={(e)=>set({description:e.target.value})}/></div><div><label className={labelClass}>Características</label><textarea className={`${inputClass} min-h-24 resize-y`} value={form.characteristics} onChange={(e)=>set({characteristics:e.target.value})}/></div><div><label className={labelClass}>Imágenes — una URL por línea</label><textarea className={`${inputClass} min-h-24 resize-y font-mono text-xs`} value={form.imageUrls} onChange={(e)=>set({imageUrls:e.target.value})}/></div></div></section>

    <section className={sectionClass}><h2 className="text-base font-bold text-gray-900">Información técnica</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div><label className={labelClass}>Resumen técnico</label><input className={inputClass} value={form.technical.summary} onChange={(e)=>setNested('technical',{summary:e.target.value})}/></div><div><label className={labelClass}>Medidas</label><input className={inputClass} value={form.technical.measures} onChange={(e)=>setNested('technical',{measures:e.target.value})}/></div><div><label className={labelClass}>Resolución</label><input className={inputClass} value={form.technical.resolution} onChange={(e)=>setNested('technical',{resolution:e.target.value})}/></div><div><label className={labelClass}>Horario encendido</label><input className={inputClass} value={form.technical.turn_on_schedule} onChange={(e)=>setNested('technical',{turn_on_schedule:e.target.value})}/></div><div><label className={labelClass}>Frecuencia diaria</label><input className={inputClass} value={form.technical.daily_frequency} onChange={(e)=>setNested('technical',{daily_frequency:e.target.value})}/></div><div><label className={labelClass}>Requisitos</label><input className={inputClass} value={form.technical.requirements} onChange={(e)=>setNested('technical',{requirements:e.target.value})}/></div><div><label className={labelClass}>Duración spot (s)</label><input className={inputClass} value={form.technical.spot_duration_seconds} onChange={(e)=>setNested('technical',{spot_duration_seconds:e.target.value})}/></div><div><label className={labelClass}>Salidas diarias mínimas</label><input className={inputClass} value={form.technical.minimum_daily_outings} onChange={(e)=>setNested('technical',{minimum_daily_outings:e.target.value})}/></div><div><label className={labelClass}>Máximo anunciantes</label><input className={inputClass} value={form.technical.max_advertisers} onChange={(e)=>setNested('technical',{max_advertisers:e.target.value})}/></div><div><label className={labelClass}>Duración ruta (h)</label><input className={inputClass} value={form.technical.route_duration_hours} onChange={(e)=>setNested('technical',{route_duration_hours:e.target.value})}/></div></div></section>

    <section className={sectionClass}><h2 className="text-base font-bold text-gray-900">Pricing</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><div><label className={labelClass}>Exhibición</label><input className={inputClass} value={form.pricing.exhibition_price} onChange={(e)=>setNested('pricing',{exhibition_price:e.target.value})}/></div><div><label className={labelClass}>Instalación</label><input className={inputClass} value={form.pricing.installation_price} onChange={(e)=>setNested('pricing',{installation_price:e.target.value})}/></div><div><label className={labelClass}>Impresión</label><input className={inputClass} value={form.pricing.printing_price} onChange={(e)=>setNested('pricing',{printing_price:e.target.value})}/></div><div><label className={labelClass}>Mensual</label><input className={inputClass} value={form.pricing.monthly_price} onChange={(e)=>setNested('pricing',{monthly_price:e.target.value})}/></div><div><label className={labelClass}>Exclusiva</label><input className={inputClass} value={form.pricing.exclusive_price} onChange={(e)=>setNested('pricing',{exclusive_price:e.target.value})}/></div><div><label className={labelClass}>Moneda</label><select className={inputClass} value={form.pricing.currency} onChange={(e)=>setNested('pricing',{currency:e.target.value})}><option value="ARS">ARS</option><option value="USD">USD</option></select></div></div></section>

    {form.family === 'led_mobile' && <section className={sectionClass}><h2 className="text-base font-bold text-gray-900">Ruta LED móvil</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><div><label className={labelClass}>Nombre de ruta</label><input className={inputClass} value={form.route.route_name} onChange={(e)=>setNested('route',{route_name:e.target.value})}/></div><div><label className={labelClass}>Horario</label><input className={inputClass} value={form.route.schedule} onChange={(e)=>setNested('route',{schedule:e.target.value})}/></div><div><label className={labelClass}>Duración</label><input className={inputClass} value={form.route.duration} onChange={(e)=>setNested('route',{duration:e.target.value})}/></div><div><label className={labelClass}>Días</label><input className={inputClass} value={form.route.weekdays} onChange={(e)=>setNested('route',{weekdays:e.target.value})}/></div><div className="md:col-span-2"><label className={labelClass}>Route Path (JSON)</label><textarea className={`${inputClass} min-h-28 resize-y font-mono text-xs`} value={form.route.routePath} onChange={(e)=>setNested('route',{routePath:e.target.value})}/></div><div className="md:col-span-2"><label className={labelClass}>Waypoints (JSON)</label><textarea className={`${inputClass} min-h-28 resize-y font-mono text-xs`} value={form.route.waypoints} onChange={(e)=>setNested('route',{waypoints:e.target.value})}/></div></div></section>}

    <div className="flex items-center justify-end gap-2 border-t border-gray-200 pt-5"><button onClick={()=>navigate('/dashboard/soportes')} className="rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-xs font-bold text-gray-700">Cancelar</button><button disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-gray-900 px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin"/> : <Save className="h-4 w-4"/>}{saving ? 'Guardando…' : 'Guardar soporte'}</button></div>
  </div></DashboardShell>;
}
